### ISSUE TITLE
Assemble v0.4.x Documentation

### ISSUE THREAD

**Issue by jonschlinkert** [assemble/assemble.io#137]
@assemble/core-team I created a branch on assemble/assemble.io with a copy of the current Assemble documentation (v0.4.x), so we it's available for anyone who doesn't or can't migrate to v0.6.0. 

Just a heads up!

**Comment by goodpixels** [comment]
I've just discovered Assemble and I'm loving it! It's brilliant, and the potential of the project is fantastic! But I have to say that the documentation is... difficult to understand. I appreciate the fact that it's a lot of work to write and maintain it on top of all the work on the Assemble itself, but I think the current state of the docs can be off-putting for some people.

I think the problem is that the documentation is being written by authors themselves, and as such is a bit opinionated. What I mean by that is that some areas of it are unclear to the newcomers. For example, it took me a good while to grasp that `options.partials` is actually responsible not only for partials themselves, but also for any `*.md` files I might want to include. I think it would be **much clearer**, if these two options were provided explicitly - considering that a lot of people like me, will make assumptions about partials being actually *chunks of code*. I wouldn't classify `*.md` files as *partials*, but rather strictly as *content* - or at least that's what makes sense to me (coming from the PHP world).

Another example of this could be the entire section on helpers. There is no clear indication of what's *included* and what's *not included* in the default setup. For example, the documentation mentions the `{{prettify}}` helper, but **doest not clearly state** that it's an external dependency. I'd suggest creating a separate section listing external helpers and avoiding referencing them in parts of the documentation which talk about built-in helpers.

On another note, it would be nice to have all external helpers published as *bower packages*. `bower_components` is where I would naturally put the helpers. Just like I'd rather have *jQuery* in `bower_components` than in `node_modules`.

Moreover, I find it a bit weird that external helpers are hosted under the *helpers* organisation. Again, I think it would be better to rename it to *assemble-helpers* or something more descriptive. At the moment, it's quite ambiguous.

So is the *Quickstart* section. I'd strongly recommend including there a sample `Gruntfile.js` along with the [Assemble example repository](https://github.com/assemble/assemble-example).

Same goes for the *Collections* and *Built-in variables* sections. There is **no clear explanation** of what the collections actually are and how to use them, aside from a few quick examples, which do assume that the reader is familiar with Assemble's concept of a collection. *Tags* and *Categories* are just the same. The documentation states:

> `tags`: List of tag objects that are associated with this page. These should be provided in the yaml header.

That's fine, but what do those tags actually do? No sample code, no explanation is provided.

I love independent projects like this one, and it's great to see how quickly it grows, but I feel there is a strong need on making the resources more objective, so people can just copy & paste and hack around. Putting everything together for the first time, was a tedious task (at least for me), but once up and running I was astonished at how flexible and easy to use Assemble really is.

Keep up the good work chaps,
John

PS. http://assemble.io is not working on the iPhone.

**Comment by jonschlinkert** [comment]
> I've just discovered Assemble and I'm loving it! It's brilliant

thanks!  We definitely appreciate the feedback, however this is all related to the current v0.4.x branch of assemble. All of the documentation is being re-written for the [upcoming release](https://github.com/assemble/assemble/tree/v0.6.0). Feedback is useful, but if you know what needs to be fixed, a PR would be much better.  

It's also good to 1) look at branches and see what kind of progress is being made, and 2) read over existing issues to see if what you're about to say has already been covered first. That way we can concentrate our energy on making progress instead of re-explaining things that were already covered in (many) other issues. 

We know the current documentation isn't the best, but we're focusing all of our energy on the upcoming release and all documentation will be re-written from the ground up. 

> I think the problem is that the documentation is being written by authors themselves, and as such is a bit opinionated.

Well, there are good reasons for that. Usually the authors know that you will get unexpected results if you don't use the application the way it was intended to be used. Also, the authors are writing code more than documentation. Again, it's always more valuable to the community to do PRs instead of "hey, you missed a spot!".

> There is no clear indication of what's included and what's not included in the default setup.

There are so many discussions about this already created as issues on assemble and related projects, I'll just allow them to speak for themselves. 

>  it would be nice to have all external helpers published as bower packages. bower_components is where I would naturally put the helpers. Just like I'd rather have jQuery in bower_components than in node_modules.

That is totally doable for any helper that can be browserified. we would take PRs with unit tests and browserfy in any of those projects. 

> I find it a bit weird that external helpers are hosted under the helpers organisation

Given that most of the helpers can be used with any node.js application and have nothing to do with assemble, what's weird about it?

> PS. http://assemble.io is not working on the iPhone

a PR would be awesome.
