### ISSUE TITLE
beard aware? 

### ISSUE THREAD

**Issue by pomke** [assemble/assemble.io#156]
Hi guys (I feel safe saying guys for this one), 

http://assemble.io/docs/About.html
(see: https://github.com/assemble/assemble.io/blob/master/templates/pages/docs/About.md.hbs#L14)

Has this odd section where you suggest that everyone is an adult, and an adult with a beard. I don't think you're intentionally othering women, young people or men who don't have or cannot grow beards but that's the effect here. 

Please consider changing this to something more appropriate, ie:

"Blog awareness"

Which really means "if you put your posts in a specific folder, and you name it exactly as required, then the parser will find your posts and render them into a blog". But Assemble isn't worried about what you put where, or where you go and how late you'll be out. You're a responsible person, Assemble allows you to make your own decisions.

**Comment by jonschlinkert** [comment]
we've had this discussion. it's going to be taken down when the docs are updated. please research existing issues first.

**Comment by jonschlinkert** [comment]
also, it's worth mentioning that the "beard" joke has existed since like the 70s. The joke is poking fun at the stereotype, not insinuating that all programmers have beards (as I clearly don't, and can't grow a beard for that matter). I feel bad if this made anyone feel alienated - but hopefully most people take it as the joke it was intended to be.
