### ISSUE TITLE
How to output a raw block?

### ISSUE THREAD

**Issue by phobia** [assemble/assemble.io#73]
Hi,

In a page I want to output a block of content without handlebars parsing anything inside it. Can it be done?

The case is that I want to embed a handlebars template for the client side javascript to use, but since some of the variables are named the same, they are parsed by handlebars through Assemble.

I'm imagining something like this:

```
{{#raw}}
<script type="text/x-handlebars-template">
    <li>{{title}}</li>
</script>
{{/raw}}
```

**Comment by doowb** [comment]
@phobia I think that Handlebars will cache the compiled partial function after it's first use, so your gist might show JavaScript functions instead of just the raw partial.

Also, [they added a way to show output "raw" templates](https://github.com/wycats/handlebars.js/pull/730) in alpha. You still have to wrap it in some type of helper, but you could change your helper to be a simple pass-through...

```
Handlebars.registerHelper('raw', function(options) {
  return options.fn();
});
```

Then if someone wants it to get compiled and rendered, they use it normally...

``` handlebars
{{raw}}
  <span>{{foo}}</span>
{{/raw}}
```

If they want it to be the raw template, the use 4 mustaches

``` handlebars
{{{{#raw}}}}
<span>{{foo}}</span>
{{{{/raw}}}}
```

**Comment by mootari** [comment]
In case anyone else runs into this problem within markdown content, this would be the solution:
```handlebars
{{{{markdown}}}}{% body %}{{{{/markdown}}}}
```
The missing `#` [is correct](http://handlebarsjs.com/expressions.html#escaping).

**Comment by landwire** [comment]
Hi there,
sorry to re-open this issue, but I think it's maybe fairly related.
Instead of trying to use raw (or markdown) like this:
```
{{{{raw}}}}
<span>{{foo}}</span>
{{{{/raw}}}}
```

I would like to output the contents of a partial (foo.hbs) in raw format:
```
{{{{raw}}}}
{{>foo}}
{{{{/raw}}}}
```

I tried this with markdown:
```
{{{{markdown}}}}
{{>foo}}
{{{{/markdown}}}}

```
and it outputs this: {{>foo}}
But I would like this: `<h1>This is the {{title}}</h1> `


foo.hbs
`<h1>This is the {{title}}</h1> `

Anybody could give me a hint on how to achieve this?
The gist here: https://gist.github.com/phobia/9110443 sometimes just returns functions as @doowb already stated, so it is no help to me.
