### ISSUE TITLE
Why are there two template libraries?

### ISSUE THREAD

**Issue by kristoferjoseph** [assemble/assemble.io#74]
Having both lodash and Handlebars seems to add unnecessary mental overhead to the project. Furthermore lodash templates are an order of magnitude faster than handlebars. Why not just use lodash everywhere?

**Comment by airtonix** [comment]
@jonschlinkert Just want to add a bit of reality here...

> Handlebars is more approachable and easy to pick up for non-javascript developers. 

It really isn't compared to the style of template language like Nunjucks, Django, Jinja, Liquid provide.

All those obscure little hashes and arrows don't really represent any amount of discoveriability outside the subculture of those in the know of handlebars.

Another detractor for handlebars, ejs, and pretty much any "partials" based template language is that they promote duplication of work over modularisation...

I for one will always shout loudly in favour of abstracting dependany on external libraries, so your choice to let the projects team choose their template engine is a good one.

**Comment by waynedpj** [comment]
> Another detractor for handlebars, ejs, and pretty much any "partials" based template language is that they promote duplication of work over modularisation... Where template languages that provide tags like extends and block <blockname> provide a far better workflow (they'll almost always provide the include <partialname> tag)

i agree that i have found a few instances where using a template languages/layouts systems w/o `extend` and `block` i ended up getting stuck with repeating parts.  however, i am a novice in the JavaScript template world.  so i was wondering if you could explain a bit more why partial-based template languages do not promote modularization, since IIUC partials are a way to do just that: modularize templates?

thanks.

**Comment by airtonix** [comment]
@waynedpj simply because partials concept does not provide the layering aspect that extends/blocks do. Simply splitting your templates into separate files is not modularisation, that's just... well splitting your files up. 

Partials won't allow you for example to trace all your templates down to a common ancestor. Jinja/Django template language will for example allow you to have this layering template ancestory with the ability to throw in multiple unique context variables for just that include chain: 

### patternlab/templates/blog/article-detail.html
```jinja
...
{% include "patternlab/molecules/blocks/block-large-related-posts.html" with Articles=Page.articles authors=Page.authors %}
...
```

### patternlab/molecules/blocks/block-large-related-posts.html
```jinja
{% extends "patternlab/atoms/blocks/block.html" %}
{% block blockClasses %}{{ block.super }} block-large-related-articles{% endblock %}
{% block blockContent %}
<h4>{{ Articles|length }} articles by {{ Authors|length }} authors</h4>
<ul>
{% for article in Articles %}
  <li><a href="{% url 'article-detail' article.pk %}">{{ article.title|escape }}</a></li>
{% endfor %}
</ul>
{% endblock %}
```

### patternlab/atoms/blocks/block.html
```jinja
<div class="block {% block blockClasses %}{% endblock %}">
{% block blockContent %}{% endblock %}
</div>
```

So now, not only does your page layout have an ancestory of templates, so does your inclusions.

**Comment by jonschlinkert** [comment]
> Partials won't allow you for example to trace all your templates down to a common ancestor

No, and that is specifically why partials are more modular and portable. When templates have **any** ancestor or dependency, or tree that can be traversed, that explicitly and decidedly makes them no longer self-contained. That makes them (potentially) dependent on other templates.

Template inheritance is powerful, but it's not necessarily the axiom of portability and modularity. In reality, whether or not they are is based on how the user implements them. In an absolute sense, partials are just as likely to be subject to a dependency tree, but they can also _not_ be.

**Comment by waynedpj** [comment]
@airtonix @jonschlinkert thanks for the opinions and insight.  a lot to learn from just following issues here.  while i really like the `block`,`extend`, inheritance features, getting the hierarchy right from the beginning is difficult (just like in OOP) and can become hard to change later.  thus, the partials and composition makes things a bit more flexible and currently what i lean towards.  however, as stated i am new to all of this.

one problem i am stuck on with standard nested layouts (as in assemble's [layouts](https://github.com/doowb/layouts)) w/o blocks is how to append stylesheets and script tags to the topmost layout from nested one?  i have some hacks using front matter, but it does feel like i am missing something.

**Comment by jonschlinkert** [comment]
@waynedpj I might have some ideas on how to do this easier now, want to create another issue to discuss?
